### ISSUE TITLE
Failed to open zip file.

### ISSUE THREAD

**Issue by FBOURAS** [piotrpolak/android-http-server#12]
For the first time, Loading file error :
Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

What todo? :/

**Comment by piotrpolak** [comment]
This is a Gradle issue or your network configuration problem, not the project itself. If you happen to have a broken Gradle ZIP consider removing the Gradle cache or at lease google the error message.
